//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theater
    {
        public int Id { get; set; }
        public string TheaterName { get; set; }
        public string TheaterDesc { get; set; }
        public string TheaterType { get; set; }
    }
}
